--- Cargo.toml.orig	2022-04-29 16:05:14 UTC
+++ Cargo.toml
@@ -22,14 +22,10 @@ serde_json = "1.0"
 sha2 = "0.9.5"
 yamlette = "0.0.8"
 tempfile = "3.3.0"
+clvm_rs = { package = "clvm_rust", git = "https://github.com/prozacchiwawa/clvm_rs", rev = "b9f9c3345243ab1d5968fd16f4a3599d0ec43699" }
 
 [patch.crates-io]
 skimmer = { git = "https://github.com/dnsl48/skimmer", rev = "ca914ef624ecf39a75ed7afef10e7838fffe9127" }
-
-[dependencies.clvm_rs]
-git = "https://github.com/prozacchiwawa/clvm_rs"
-branch = "20211029-try-config"
-package = "clvm_rust"
 
 [target.x86_64-apple-darwin]
 rustflags = [
